[2025-04-16 16:05:20,576] INFO [NodeToControllerChannelManager id=1 name=registration] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2025-04-16 16:24:38,384] WARN Failed atomic move of E:\SNS_MSA\kafka\kafka-logs\replication-offset-checkpoint.tmp to E:\SNS_MSA\kafka\kafka-logs\replication-offset-checkpoint retrying with a non-atomic move (org.apache.kafka.common.utils.Utils)
java.nio.file.AccessDeniedException: E:\SNS_MSA\kafka\kafka-logs\replication-offset-checkpoint.tmp -> E:\SNS_MSA\kafka\kafka-logs\replication-offset-checkpoint
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:328) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291) ~[?:?]
	at java.base/java.nio.file.Files.move(Files.java:1430) ~[?:?]
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:941) ~[kafka-clients-4.0.0.jar:?]
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:927) ~[kafka-clients-4.0.0.jar:?]
	at org.apache.kafka.server.common.CheckpointFile.write(CheckpointFile.java:86) ~[kafka-server-common-4.0.0.jar:?]
	at org.apache.kafka.storage.internals.checkpoint.CheckpointFileWithFailureHandler.write(CheckpointFileWithFailureHandler.java:53) ~[kafka-storage-4.0.0.jar:?]
	at org.apache.kafka.storage.internals.checkpoint.OffsetCheckpointFile.write(OffsetCheckpointFile.java:61) ~[kafka-storage-4.0.0.jar:?]
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$7(ReplicaManager.scala:2460) ~[kafka_2.13-4.0.0.jar:?]
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$7$adapted(ReplicaManager.scala:2460) ~[kafka_2.13-4.0.0.jar:?]
	at scala.Option.foreach(Option.scala:437) ~[scala-library-2.13.15.jar:?]
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$6(ReplicaManager.scala:2460) ~[kafka_2.13-4.0.0.jar:?]
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$6$adapted(ReplicaManager.scala:2459) ~[kafka_2.13-4.0.0.jar:?]
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619) ~[scala-library-2.13.15.jar:?]
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617) ~[scala-library-2.13.15.jar:?]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935) ~[scala-library-2.13.15.jar:?]
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:905) ~[scala-library-2.13.15.jar:?]
	at kafka.server.ReplicaManager.checkpointHighWatermarks(ReplicaManager.scala:2459) ~[kafka_2.13-4.0.0.jar:?]
	at kafka.server.ReplicaManager.$anonfun$startHighWatermarkCheckPointThread$1(ReplicaManager.scala:369) ~[kafka_2.13-4.0.0.jar:?]
	at org.apache.kafka.server.util.KafkaScheduler.lambda$schedule$1(KafkaScheduler.java:151) ~[kafka-server-common-4.0.0.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[2025-04-16 16:54:38,380] WARN Failed atomic move of E:\SNS_MSA\kafka\kafka-logs\replication-offset-checkpoint.tmp to E:\SNS_MSA\kafka\kafka-logs\replication-offset-checkpoint retrying with a non-atomic move (org.apache.kafka.common.utils.Utils)
java.nio.file.AccessDeniedException: E:\SNS_MSA\kafka\kafka-logs\replication-offset-checkpoint.tmp -> E:\SNS_MSA\kafka\kafka-logs\replication-offset-checkpoint
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:328) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291) ~[?:?]
	at java.base/java.nio.file.Files.move(Files.java:1430) ~[?:?]
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:941) ~[kafka-clients-4.0.0.jar:?]
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:927) ~[kafka-clients-4.0.0.jar:?]
	at org.apache.kafka.server.common.CheckpointFile.write(CheckpointFile.java:86) ~[kafka-server-common-4.0.0.jar:?]
	at org.apache.kafka.storage.internals.checkpoint.CheckpointFileWithFailureHandler.write(CheckpointFileWithFailureHandler.java:53) ~[kafka-storage-4.0.0.jar:?]
	at org.apache.kafka.storage.internals.checkpoint.OffsetCheckpointFile.write(OffsetCheckpointFile.java:61) ~[kafka-storage-4.0.0.jar:?]
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$7(ReplicaManager.scala:2460) ~[kafka_2.13-4.0.0.jar:?]
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$7$adapted(ReplicaManager.scala:2460) ~[kafka_2.13-4.0.0.jar:?]
	at scala.Option.foreach(Option.scala:437) ~[scala-library-2.13.15.jar:?]
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$6(ReplicaManager.scala:2460) ~[kafka_2.13-4.0.0.jar:?]
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$6$adapted(ReplicaManager.scala:2459) ~[kafka_2.13-4.0.0.jar:?]
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619) ~[scala-library-2.13.15.jar:?]
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617) ~[scala-library-2.13.15.jar:?]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935) ~[scala-library-2.13.15.jar:?]
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:905) ~[scala-library-2.13.15.jar:?]
	at kafka.server.ReplicaManager.checkpointHighWatermarks(ReplicaManager.scala:2459) ~[kafka_2.13-4.0.0.jar:?]
	at kafka.server.ReplicaManager.$anonfun$startHighWatermarkCheckPointThread$1(ReplicaManager.scala:369) ~[kafka_2.13-4.0.0.jar:?]
	at org.apache.kafka.server.util.KafkaScheduler.lambda$schedule$1(KafkaScheduler.java:151) ~[kafka-server-common-4.0.0.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[2025-04-16 16:55:20,488] INFO [SnapshotGenerator id=1] Creating new KRaft snapshot file snapshot 00000000000000061356-0000000010 because we have waited at least 60 minute(s). (org.apache.kafka.image.publisher.SnapshotGenerator)
[2025-04-16 16:55:20,519] INFO [SnapshotEmitter id=1] Successfully wrote snapshot 00000000000000061356-0000000010 (org.apache.kafka.image.publisher.SnapshotEmitter)
